### ISSUE TITLE
Wrong size inference when writing to buffer

### ISSUE THREAD

**Issue by reczkok** [software-mansion/TypeGPU#307]
```ts
import tgpu from 'typegpu';
import { vec3f } from 'typegpu/data';

const adapter = await navigator.gpu.requestAdapter();
const device = await adapter?.requestDevice();

if (!device ) throw new Error();

const b = tgpu.createBuffer(vec3f).$device(device);

tgpu.write(b, vec3f(2,2,2))
```
Results in:
```
Write range (bufferOffset: 0, size: 16) does not fit in [Buffer (unlabeled)] size (12).
 - While calling [Queue].WriteBuffer([Buffer (unlabeled)], (0 bytes), data, (16 bytes))
```

**Comment by reczkok** [comment]
In this particular example we have a buffer that has just a `vec3f` so the size is 12 bytes. When we write to a buffer we determine the size by rounding up the size by the alignment. This is correct for structs, arrays and matrices (which are essentially arrays). Primitive types, however, do not have such behavior. It happens to not make a difference for any other data apart from `vec3f` as it is the only primitive type that has a different alignment than size.

**Comment by iwoplaza** [comment]
Nice catch! 🙌
