### ISSUE TITLE
See if the "WGSL Literal" VSCode plugin can be embedded into the examples page.

### ISSUE THREAD

**Issue by iwoplaza** [software-mansion/TypeGPU#354]
This would allow for WGSL syntax highlighting for WGSL template literals:
```ts
/* wgsl */ `1 + 2`
```

**Comment by reczkok** [comment]
I think it will be very difficult to do in Monaco alone. The VSCode plugin will not work here as it depends on the VSCode API. I think it is possible but not in a straightforward way - unless there is a way to have a multi language `Model` inside Monaco. As far as my research went, the only way I think it could be done is having the editor split the text and display it multiple `Models`.
