### ISSUE TITLE
Allow more than one positional argument in tgpu-cli/tgpu-gen.

### ISSUE THREAD

**Issue by iwoplaza** [software-mansion/TypeGPU#500]
```bash
npx tgpu-gen file1.wgsl file2.wgsl file3.wgsl (args)
# same as
npx tgpu-gen file1.wgsl (args)
npx tgpu-gen file2.wgsl (args)
npx tgpu-gen file3.wgsl (args)
```

**Comment by mhawryluk** [comment]
Closing for now, it generates too many problems and adds too much complexity, as of now.
- when there are multiple inputs should there be multiple outputs also and how
- watch mode - what if one file is matched by more than one input pattern?
