### ISSUE TITLE
Add complete example of compute shader usage

### ISSUE THREAD

**Issue by afternoon2** [software-mansion/TypeGPU#706]
Hey, I managed to run my compute shader with tgpu (🎉 ), but I struggled a bit because of lack of explicit example of how to read the data in the docs page. I found the solution in the MNIST Inference demo in the end, but this required digging into the code. Maybe it's worth to add a simple example to the docs as well?

What I mean, is a complete snippet of setting up a readable and mutable buffers, creating bindGroupLayout, populating it to a bind group and running a compute pass. At first, I didn't know I also need to invoke `device.queue.onSubmittedWorkDone` (I haven't used that in my vanilla version).

WDYT?

**Comment by reczkok** [comment]
Hi there! Thanks for trying out TypeGPU. Could you provide some code context for the situation when it failed without `onSubmittedWorkDone`? In theory it should have worked exactly the same as in your vanilla version if the order of operations was the same. The only reason I can think of for the need to wait would be that when you read using our `.read` utility a separate command encoder is created. So if you had your vanilla reading operations originally inside the same encoder as the shader pass the order of operations should be guaranteed which is not the case with two separate command encoders. This is just a theory tho and I would need to dig deeper to find out the exact reason.

**Comment by reczkok** [comment]
When I found out exactly what is causing this I think adding a chapter about it in the docs is a great idea.

**Comment by afternoon2** [comment]
Ok, apologies. I simply forgot to add `root.device.queue.submit([commandEncoder.finish()]);`, that's why it wasn't working 🤦🏻  We can close this issue.
