### ISSUE TITLE
Add code editor to the Home page in wigsill-examples ("Inspector")

### ISSUE THREAD

**Issue by mhawryluk** [software-mansion/TypeGPU#97]
The Home page in `wigsill-examples` presents the resolved code from `sampleShader.ts`. We should add a code editor just like the one in the example pages, that would allow the user to type in wigsill code and see the resolved version above in real time.

![Image](https://github.com/user-attachments/assets/1786f858-2ccc-434e-928d-da883300a93c)

**Comment by iwoplaza** [comment]
Use WebGPU inspector instead 💜
